FROM oven/bun:latest

WORKDIR /app

COPY package.json .
COPY bun.lockb .

COPY drizzle.config.ts .
COPY drizzle ./drizzle
COPY src/lib/server/db ./src/lib/server/db

RUN bun install drizzle-kit drizzle-orm

ENTRYPOINT [ "bun", "run", "db:migrate" ]