FROM oven/bun:latest

WORKDIR /app

COPY package.json ./
COPY bun.lockb ./

COPY drizzle ./
COPY drizzle.config.ts ./
COPY src/lib/server/db ./

RUN bun install drizzle-kit

ENTRYPOINT [ "bun", "run", "db:migrate" ]